from tools.society_of_mind.society_of_mind import thinking


class Thinking:
    description = "Thinking more about a topic. For any topic, call on this tool to "\
        + "think more about it. This should be done used for every non-trivial "\
        + "question or topic that requires more thought. This tool will help you "\
        + "think more deeply about a topic and provide more insights."
                       
    # arguments into the tool (generated by the LLM)
    # defines what the agent must generate to input into the tool 
    properties = {
        # arg 1: section of memory to edit
        "query": {
            "type": "string",
            "description": "Thinking about a query",
        }
    }
    
    def run(query):
        print(f'Thinking about: {query}\n')
        results = thinking(query)
        print(f'Results: {results}\n')
        return results