from tools.search.google_search import SearchTool


class Search:
    description = "Tool to run web searches using Google, whenever you want " \
                         + "to obtain up to date information beyond your training and "\
                         + "provide accurate information on any topic."
                        

    # arguments into the tool (generated by the LLM)
    # defines what the agent must generate to input into the tool 
    properties = {
        # arg 1: section of memory to edit
        "query": {
            "type": "string",
            "description": "Search query"
        }
    }
    
    google_search = SearchTool()
    
    def run(query):
        print(f'\nSearching on {query}')
        results = Search.google_search.run(query)
        print(f'Results: {results}\n')
        return results
    
        