from webbrowser import open as open_page

class Browser:
    description = "Open local web browser with website URL"
                        

    # arguments into the tool (generated by the LLM)
    # defines what the agent must generate to input into the tool 
    properties = {
        # arg 1: section of memory to edit
        "url": {
            "type": "string",
            "description": "URL for site to open"
        }
    }
    
    def run(url):
        open_page(url, new=0)
        return f'url opened'
    